-- Flyway Migration: V1__create_order_tables.sql

CREATE TABLE `order_head`
(
    `serial_id`          INT(11) UNSIGNED          DEFAULT '0' COMMENT 'Financial sequence number, display only, not used in logic',
    `order_head_id`      INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key ID',
    `check_number`       INT(11)                   DEFAULT NULL COMMENT 'Check number, resets daily',
    `rvc_center_id`      INT(11)                   DEFAULT NULL COMMENT 'Restaurant zone ID (e.g., Chinese/Western)',
    `rvc_center_name`    VARCHAR(30)               DEFAULT NULL COMMENT 'Restaurant zone name',
    `table_id`           INT(11)                   DEFAULT NULL COMMENT 'Table ID',
    `table_name`         VARCHAR(30)               DEFAULT NULL COMMENT 'Table name',
    `check_id`           INT(11)          NOT NULL DEFAULT '0' COMMENT 'Split check ID',
    `open_employee_id`   INT(11)                   DEFAULT NULL COMMENT 'Employee who opened the table',
    `open_employee_name` VARCHAR(30)               DEFAULT NULL COMMENT 'Name of the employee who opened the table',
    `customer_num`       INT(11)                   DEFAULT NULL COMMENT 'Number of guests',
    `customer_id`        INT(11)                   DEFAULT '0' COMMENT 'Customer source: 1-WeChat, 2-Phone, 3-Fast food, 4-Local table',
    `customer_name`      VARCHAR(30)               DEFAULT NULL COMMENT 'Membership card number',
    `pos_device_id`      INT(11)                   DEFAULT NULL COMMENT 'POS device ID',
    `pos_name`           VARCHAR(30)               DEFAULT NULL COMMENT 'POS terminal name',
    `order_start_time`   DATETIME                  DEFAULT NULL COMMENT 'Order start time',
    `order_end_time`     DATETIME                  DEFAULT NULL COMMENT 'Order close time',
    `should_amount`      DECIMAL(11, 2)            DEFAULT '0.00' COMMENT 'Amount due (pre-payment: remaining balance, post-payment: actual due)',
    `return_amount`      DECIMAL(11, 2)            DEFAULT '0.00' COMMENT 'Amount for returned items (likely unused)',
    `discount_amount`    DECIMAL(11, 2)            DEFAULT '0.00' COMMENT 'Discount amount',
    `actual_amount`      DECIMAL(11, 2)            DEFAULT '0.00' COMMENT 'Amount actually received',
    `print_count`        INT(11)                   DEFAULT '0' COMMENT 'Number of times the bill was printed',
    `status`             INT(11)                   DEFAULT '0' COMMENT 'Status: 0-Unpaid, 1-Paid, 2-Printed',
    `eat_type`           INT(11)                   DEFAULT '0' COMMENT 'Dining type: 0-Dine-in, 1-Takeout, 2-Delivery',
    `check_name`         VARCHAR(30)               DEFAULT NULL COMMENT 'Bill name',
    `original_amount`    DECIMAL(11, 2)            DEFAULT '0.00' COMMENT 'Original amount before discount (excludes returns)',
    `service_amount`     DECIMAL(11, 2)            DEFAULT '0.00' COMMENT 'Service fee',
    `edit_time`          DATETIME                  DEFAULT NULL COMMENT 'Reversal time',
    `party_id`           INT(11)                   DEFAULT NULL COMMENT 'Linked party table ID',
    `edit_employee_name` VARCHAR(30)               DEFAULT NULL COMMENT 'Reversal employee name',
    `remark`             VARCHAR(150)              DEFAULT NULL COMMENT 'Table-level remark',
    `is_make`            INT(11)                   DEFAULT NULL COMMENT 'Whether the order is prepared',
    `delivery_info`      VARCHAR(255)              DEFAULT NULL COMMENT 'Delivery information',
    `kds_show`           INT(11)                   DEFAULT '0' COMMENT 'Whether to display on kitchen screen',
    `kds_time`           DATETIME                  DEFAULT NULL COMMENT 'Kitchen screen timestamp',
    `tax_amount`         DECIMAL(11, 2)            DEFAULT '0.00' COMMENT 'Tax amount',
    `raw_talbe`          INT(11)                   DEFAULT '0' COMMENT 'Original table ID when combining tables',
    `tips_amount`        DECIMAL(11, 2)            DEFAULT '0.00' COMMENT 'Tips amount',
    `member_discount`    DECIMAL(11, 2)            DEFAULT '0.00' COMMENT 'Membership discount',
    `delivery_fee`       DECIMAL(11, 2)            DEFAULT '0.00' COMMENT 'Delivery fee (not included in should/actual)',
    `seller_id`          INT(11)                   DEFAULT NULL COMMENT 'Seller who made the wholesale. From the employee table, but not using a foreign key, so it’s not affected by deletions or modifications.',
    PRIMARY KEY (`order_head_id`, `check_id`),
    KEY `table_id` (`table_id`) USING BTREE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8 COMMENT ='Order header table';

CREATE TABLE `order_detail`
(
    `order_detail_id`       INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key for order detail',
    `order_head_id`         INT(11)       DEFAULT NULL COMMENT 'Linked order header ID',
    `check_id`              INT(11)       DEFAULT '1' COMMENT 'Split check identifier',
    `menu_item_id`          INT(11)       DEFAULT NULL COMMENT 'Menu item ID (-1 service fee, -2 discount, etc.)',
    `menu_item_name`        VARCHAR(60)   DEFAULT NULL COMMENT 'Menu item name',
    `product_price`         DOUBLE(15, 2) DEFAULT NULL COMMENT 'Item price or change amount',
    `is_discount`           BIT(1)        DEFAULT NULL COMMENT 'Whether it is a complimentary item',
    `original_price`        DOUBLE(15, 2) DEFAULT NULL COMMENT 'Original price before adjustment',
    `discount_id`           INT(11)       DEFAULT NULL COMMENT 'Discount type or payment method',
    `actual_price`          DOUBLE(15, 2) DEFAULT NULL COMMENT 'Final price after discount',
    `is_return_item`        BIT(1)        DEFAULT b'0' COMMENT 'Whether the item was returned',
    `order_employee_id`     INT(11)       DEFAULT NULL COMMENT 'Employee who placed the order',
    `order_employee_name`   VARCHAR(40)   DEFAULT NULL COMMENT 'Ordering employee name',
    `pos_device_id`         INT(11)       DEFAULT NULL COMMENT 'POS terminal ID',
    `pos_name`              VARCHAR(30)   DEFAULT NULL COMMENT 'POS terminal name',
    `order_time`            DATETIME      DEFAULT NULL COMMENT 'Order time',
    `return_time`           DATETIME      DEFAULT NULL COMMENT 'Return time',
    `return_reason`         VARCHAR(200)  DEFAULT NULL COMMENT 'Return reason',
    `unit`                  VARCHAR(30)   DEFAULT NULL COMMENT 'Unit of measure',
    `weight_entry_required` BIT(1)        DEFAULT NULL COMMENT 'Whether scale entry is required',
    `quantity`              FLOAT         DEFAULT '1' COMMENT 'Quantity or weight',
    `is_send`               BIT(1)        DEFAULT NULL COMMENT 'Whether sent to kitchen',
    `condiment_belong_item` INT(11)       DEFAULT NULL COMMENT 'Belongs to main item ID',
    `eat_type`              INT(11)       DEFAULT '0' COMMENT 'Dining type',
    `auth_id`               INT(11)       DEFAULT NULL COMMENT 'Return authorization employee ID',
    `auth_name`             VARCHAR(40)   DEFAULT '' COMMENT 'Authorization employee name',
    `description`           VARCHAR(250)  DEFAULT NULL COMMENT 'Remarks',
    `n_service_type`        INT(11)       DEFAULT NULL COMMENT 'Service level',
    `not_print`             INT(11)       DEFAULT NULL COMMENT 'Whether to exclude from bill print (1=don’t print)',
    `seat_num`              INT(11)       DEFAULT NULL COMMENT 'Western dining seat number or tip recipient ID',
    `discount_price`        DOUBLE(15, 2) DEFAULT NULL COMMENT 'Discount amount',
    `sales_amount`          DOUBLE(15, 2) DEFAULT NULL COMMENT 'Sales amount after discount',
    `is_make`               INT(11)       DEFAULT NULL COMMENT 'Preparation status (0-pending, 1-done, etc.)',
    `print_class`           INT(11)       DEFAULT NULL COMMENT 'Menu family group ID',
    `rush`                  INT(11)       DEFAULT '0' COMMENT 'Rush count',
    `ready_qty`             DOUBLE(15, 2) DEFAULT NULL COMMENT 'Quantity ready',
    `end_time`              DATETIME      DEFAULT NULL COMMENT 'Preparation end time',
    `the_cook_id`           INT(11)       DEFAULT '0' COMMENT 'Cook/technician ID',
    `start_time`            DATETIME      DEFAULT NULL COMMENT 'Preparation start time',
    `choose_reason`         VARCHAR(200)  NOT NULL DEFAULT '' COMMENT 'Reservation remark',
    `seller_id`             INT           DEFAULT NULL COMMENT 'Salesperson ID, only one per order, not using a foreign key',
    `change_seller_reason`  VARCHAR(200)  NOT NULL DEFAULT '' COMMENT 'Reason for changing the salesperson',
    `commision_skiller`     FLOAT         NOT NULL DEFAULT 0 COMMENT 'Technician commission amount',
    `commision_seller`      FLOAT         NOT NULL DEFAULT 0 COMMENT 'Salesperson commission amount',
    PRIMARY KEY (`order_detail_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8 COMMENT ='Order detail table';