-- Flyway Migration: V4__create_tender_media_table.sql

CREATE TABLE `tender_media`
(
    `tender_media_id`              int(11)     NOT NULL DEFAULT '0',
    `tender_media_name`            varchar(30)          DEFAULT NULL,
    `tender_media_name2`           varchar(30)          DEFAULT NULL,
    `type`                         int(11)              DEFAULT NULL,
    `date_from`                    datetime             DEFAULT NULL,
    `date_to`                      datetime             DEFAULT NULL,
    `slu`                          int(11)              DEFAULT NULL,
    `print_class`                  int(11)              DEFAULT NULL,
    `menu_level_class`             int(11)              DEFAULT NULL,
    `privilege`                    int(11)              DEFAULT NULL,
    `category`                     int(11)              DEFAULT NULL,
    `nlu`                          varchar(20)          DEFAULT NULL,
    `open_drawer`                  bit(1)               DEFAULT NULL,
    `currency_conversion`          bit(1)               DEFAULT NULL,
    `reference_required`           bit(1)               DEFAULT NULL,
    `exempt_service`               bit(1)               DEFAULT NULL,
    `employee_meal`                bit(1)               DEFAULT NULL,
    `paid_full`                    bit(1)               DEFAULT NULL,
    `require_amount_entry`         bit(1)               DEFAULT NULL,
    `declare_tips_paid`            bit(1)               DEFAULT NULL,
    `item_is_shareable`            bit(1)               DEFAULT NULL,
    `gross_receipts`               bit(1)               DEFAULT NULL,
    `charge_receipts`              bit(1)               DEFAULT NULL,
    `cash_register_credit`         bit(1)               DEFAULT NULL,
    `tax_exempt_coupon`            bit(1)               DEFAULT NULL,
    `charged_tip`                  int(11)              DEFAULT NULL,
    `enable_halo`                  bit(1)               DEFAULT NULL,
    `halo_limits_amount`           int(11)              DEFAULT '0',
    `halo_limits_overtender`       int(11)              DEFAULT NULL,
    `halo`                         int(11)              DEFAULT NULL,
    `print_summary_totals`         bit(1)               DEFAULT NULL,
    `print_vat_lines`              bit(1)               DEFAULT NULL,
    `print_sales_itemizer`         bit(1)               DEFAULT NULL,
    `print_check_trailer`          bit(1)               DEFAULT NULL,
    `print_on_receipt`             bit(1)               DEFAULT NULL,
    `print_with_lookup`            bit(1)               DEFAULT NULL,
    `print_validation`             bit(1)               DEFAULT NULL,
    `print_endorsement`            bit(1)               DEFAULT NULL,
    `suppress_trailer`             bit(1)               DEFAULT NULL,
    `print_fiscal_cash`            bit(1)               DEFAULT NULL,
    `print_check`                  bit(1)               DEFAULT NULL,
    `print_memo_check`             bit(1)               DEFAULT NULL,
    `print_shared_check`           bit(1)               DEFAULT NULL,
    `print_check_active_seat`      bit(1)               DEFAULT NULL,
    `reprint_check`                bit(1)               DEFAULT NULL,
    `period_class_id`              int(11)              DEFAULT NULL,
    `rvc_class_id`                 int(11)              DEFAULT NULL,
    `extra_amout`                  float                DEFAULT '0',
    `staff_hold`                   bit(1)      NOT NULL DEFAULT b'0',
    `second_currency`              bit(1)      NOT NULL DEFAULT b'0',
    `second_currency_symbol`       varchar(20) NOT NULL DEFAULT '',
    `second_currency_exrate_base`  float                DEFAULT '1',
    `second_currency_exrate_value` float                DEFAULT '0',
    `second_currency_exrate`       float       NOT NULL DEFAULT '0',
    `second_currency_min_val`      float       NOT NULL DEFAULT '0',
    `shown`                        bit(1)               DEFAULT b'1',
    `is_kiosk`                     bit(1)               DEFAULT b'0',
    `kiosk_hint_1`                 varchar(200)         DEFAULT NULL,
    `kiosk_hint_2`                 varchar(200)         DEFAULT NULL,
    `kiosk_hint_3`                 varchar(200)         DEFAULT NULL,
    `kiosk_icon`                   varchar(200)         DEFAULT NULL,
    `kiosk_picture`                varchar(200)         DEFAULT NULL,
    `param1`                       int(11)              DEFAULT NULL,
    PRIMARY KEY (`tender_media_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;